#!/usr/bin/env bash
set -e

cd "$(git rev-parse --show-toplevel)"

while IFS= read -r -d '' path; do
    case "$path" in
        *.c|*.cpp|*.h|*.hpp) ;;
        *) continue ;;
    esac

    clang-format -i -- "$path"
    git add -- "$path"
done < <(git diff --cached --name-only --diff-filter=ACMR -z)
