.SUFFIXES:
.PHONY: all clean

PROJECTS := runtime init fib logger primes sleeper

all:
	@ make -C runtime
	@ make -C init
	@ make -C fib
	@ make -C logger
	@ make -C primes
	@ make -C sleeper

clean:
	@ make -C runtime clean
	@ make -C init clean
	@ make -C fib clean
	@ make -C logger clean
	@ make -C primes clean
	@ make -C sleeper clean



